### ISSUE TITLE
Programming paradigm & style

### ISSUE THREAD

**Issue by ohno** [ohno/Antique.jl#11]
This is a continuation of previous discussions #3 .

**Comment by ohno** [comment]
@hyrodium 

Thank you for your comments and discussion. I am planning to rewrite codes as multi-dispatch style before adding new models. Please see a [notebook on gist](https://gist.github.com/ohno/167858d23193e932af10fac8f08aa9a4). I have considered multi-dispatch style with reference to your [past comment](https://github.com/ohno/Antique.jl/issues/3#issuecomment-1850032249
).

Multi-dispatch coding allows to adapt Symbolics.jl, Measurements.jl, etc. I am not going to specify a type of the struct to adapt these packages.

Although the internal implementation a little loses its similarity to formulae, the usage is similar to formulas. For example, the energies of $\mathrm{H}$ and $\mathrm{He}^+$ are occasionally wrriten as $E(\mathrm{H})$ and $E(\mathrm{He}^+)$. In the multi-dispatch version, we can write it like this:

```julia
H = HydrogenAtom(Z=1)
E(H)
```
```julia
He⁺ = Hydrogen Atom(Z=2)
E(He⁺)
````

There are some undecided matters.
- Should multi-dispatch be applied to Hermitian polynomials `H(x)` as well?
- Should codes be into a module?
  - Modules are useful for document build.
  - The module name and the type name conflict. What should I name the module?
  - Not necessarily for multi-dispatch Hermitian polynomials.
- etc...

The multi-dispatch version is scheduled to be released as v0.2.0. I will continue to support `antique()` as a deprecated function and display an alert.

**Comment by ohno** [comment]
@hyrodium 
I rewrote all of codes, documents and tests for multi-dispatch style. There was [a small problem](https://github.com/ohno/Antique.jl/actions/runs/7712324652/job/21019623885#step:6:294) but it passed tests. These will be merged and released as v.0.2.0. Thank you again for your advices.

**Comment by hyrodium** [comment]
Great job! Looking forward to seeing you in JuliaTokyo :smile:
