### ISSUE TITLE
Pöschl-Teller potential

### ISSUE THREAD

**Issue by lhapp27** [ohno/Antique.jl#23]
I think it is interesting to add the [Pöschl-Teller potential](https://en.wikipedia.org/wiki/P%C3%B6schl%E2%80%93Teller_potential). It is mentioned in the [list of analytical solutions](https://en.wikipedia.org/wiki/List_of_quantum-mechanical_systems_with_analytical_solutions). It has only one parameter which controls the number of bound states, whose wave function is given in terms of associated (or generalized) Legendre functions. The eigenvalues are also a simple function of that parameter.

**Comment by lhapp27** [comment]
Thank you for your comment, but I'm not sure if I fully understand. Of course, I am happy to provide better information in the documentation about the fact that the results from the code are dimensionless, and how one can get a dimensionful Schrödinger equation with all dimensionful variables back from the dimensionless one(s). However, I feel that as long as I dont know the units from the input parameters, I cannot provide units for the output parameters, unless we introduce some kind of unit conversion.

As an example: for the Harmonic Oscillator I can provide dimensionless energy levels $n+1/2 = 0.5, 1.0, 1.5, \ldots$, which are then given in units of $\hbar \omega$ (I agree that it needs to be clearly stated/documented). If on the other hand, the factor $\hbar \omega$ is included in the output, I expect the output to not be pure numbers but have some units, e.g. $0.5\ \mathrm{J}$ or $1.5\ \mathrm{eV}$. Maybe I am missing something here, though.

I get the point about consistency and will replace ```lambda``` by ```λ```.

**Comment by ohno** [comment]
Nondimensionalization is a difficult topic. In Antique.jl inputs and outputs are pure numbers. Units are omitted. (I think it is possible to perform calculations with units using [Unitful.jl](https://painterqubits.github.io/Unitful.jl/stable/), but I have not tried it.) I have good example in hydrogen atom. Here are two examples for hydrogen atoms.
| Input | Output |
| - | - |
| $1 E_\mathrm{h} = 1 E_\mathrm{h}$ | $E_{1s} = -0.5 E_\mathrm{h}$ |
| $1 E_\mathrm{h} = 27.211386245~988\mathrm{eV}$ | $E_{1s} = -13.605693122994\mathrm{eV}$ |

These examples are calculated using Antique.jl as follows:
```julia
julia> H = HydrogenAtom(Eₕ=1.0)
julia> E(H)
-0.5

julia> H = HydrogenAtom(Eₕ=27.211386245988)
julia> E(H)
-13.605693122994
```

In a harmonic oscillator, the unit of energy is $\hbar\omega$ and it changes depending on ℏ, k and m. The case of Pöschl-Teller potential is more complicated. We have to reverse the equation before it was non-dimensionalized.

The "Reverse-Non-Dimensionalization" for enegy, potential and wavefunction are written as

```math
E_n = E_\mathrm{char} E_n^* = - \frac{\hbar^2}{2 m x_0^2} \frac{\mu^2}{2},
```

```math
V(x)
= E_\mathrm{char} V^*(x^*)
= - \frac{\hbar^2}{2 m x_0^2} \frac{\lambda(\lambda+1)}{2} \mathrm{sech}(x^*)^2,
```

```math
\psi_n(x)
= \frac{1}{\sqrt{x_0}} \psi^*_n(x^*)
= \frac{1}{\sqrt{x_0}} P_\lambda^\mu(\tanh (x^*)) \sqrt{\mu \frac{\Gamma(\lambda-\mu+1)}{\Gamma(\lambda+\mu+1)}}.
```

Your original difinitions are without the asterisk. Therefore, the model is identified by the tuple of $\hbar$, $m$, $x_0$ and $\lambda$. The unit of enegy is $E_\mathrm{char}$ and it changes depending on  $\hbar$, $m$, $x_0$. 

The proof is below. Characteristic parameters are $E_\mathrm{char} = \frac{\hbar^2}{2 m x_0^2}$ and $x_0$. Non-dimentionalization of variables are written as

```math
E^* = E / E_\mathrm{char},
```

```math
x^* = x / x_0.
```

Non-dimentionalization of operators are written as

```math
\mathrm{d}x = x_0 \mathrm{d}x^*,
```

```math
\begin{aligned}
\frac{\mathrm{d}}{\mathrm{d} x}
=
\frac{\mathrm{d} x^*}{\mathrm{d} x}
\frac{\mathrm{d}}{\mathrm{d}  x^*}
=
\frac{1}{x_0}
\frac{\mathrm{d}}{\mathrm{d}  x^*},
\end{aligned}
```

```math
\frac{\mathrm{d}^2}{\mathrm{d} x^2}
=
\frac{1}{x_0 ^2}
\frac{\mathrm{d}^2}{\mathrm{d} {x^*}^2}.
```

The kinetic energy operator and potential energy function are transformed to their original (non-dimentionalized) definitions using Schrödinger equation:

```math
\begin{aligned}
\hat{H} \psi &= E \psi
\\
\left[
-\frac{\hbar^2}{2m} \frac{\mathrm{d}^2}{\mathrm{d} x^2} - E_\mathrm{char}\frac{\lambda(\lambda+1)}{2} \mathrm{sech}(x / x_0)^2 \right] \psi &=  E \psi
\\
\left[
-\frac{\hbar^2}{2m x_0^2} \frac{\mathrm{d}^2}{\mathrm{d} {x^*}^2} - E_\mathrm{char}\frac{\lambda(\lambda+1)}{2} \mathrm{sech}(x / x_0)^2 \right] \psi &=  E \psi
\\
\left[
-\frac{1}{E_\mathrm{char}} \frac{\hbar^2}{2m x_0^2} \frac{\mathrm{d}^2}{\mathrm{d} {x^*}^2} - \frac{E_\mathrm{char}}{E_\mathrm{char}} \frac{\lambda(\lambda+1)}{2} \mathrm{sech}(x / x_0)^2 \right] \psi &=  \frac{E}{E_\mathrm{char}} \psi
\\
\left[
-\frac{1}{2} \frac{\mathrm{d}^2}{\mathrm{d} {x^*}^2} - \frac{\lambda(\lambda+1)}{2} \mathrm{sech}(x^*)^2
\right] \psi &= E^* \psi
\end{aligned}
```

The wavefunction is non-dimentionalized using normalization condition:

```math
\begin{aligned}
\int |\psi(x)|^2 \mathrm{d}x = 1
\\
\int |\psi(x)|^2 x_0 \mathrm{d}x^* = 1
\\
\int \left| \frac{1}{\sqrt{x_0}} \psi^*(x^*) \right|^2 x_0 \mathrm{d}x^* = 1
\\
\int |\psi^*(x^*)|^2 \mathrm{d}x^* = 1.
\end{aligned}
```
