### ISSUE TITLE
typo in the harmonic oscillator documentation

### ISSUE THREAD

**Issue by ajarifi** [ohno/Antique.jl#27]
HarmonicOscillator(α=1.0, m=1.0, ℏ=1.0).
α should be replaced by k.
Like this: HarmonicOscillator(k=1.0, m=1.0, ℏ=1.0).

**Comment by ohno** [comment]
https://github.com/ohno/Antique.jl/commit/323f795c2cb7cf70a2442b36f31955084340d421
