### ISSUE TITLE
Update Developer's Guide

### ISSUE THREAD

**Issue by ohno** [ohno/Antique.jl#29]
There are several unclear instructions.
- https://ohno.github.io/Antique.jl/stable/#Developer's-Guide
- https://github.com/ohno/Antique.jl?tab=readme-ov-file#developers-guide

**Comment by ajarifi** [comment]
All tests will be executed by executing include("./developer/test.jl").

I think we should add "executing include("./developer/test.jl") in the terminal".

I somehow ran it in the "dev.ipynb" and had some errors.

**Comment by ohno** [comment]
Thank you so much! I will update Antique.jl to v0.4.0 soon as the Peschel-Teller potential implementation is complete. I will rewrite guide after updating.

**Comment by ajarifi** [comment]
import Pkg; Pkg.add("Weave")
using Weave

I think I also need to add "import Pkg; Pkg.add("Weave")" before using Weave in jmd2md.jl.
I always have an error when running include("./developer/docs.jl")

**Comment by ajarifi** [comment]
by the way, testing does not take 2 minutes. but, it is much longer.

**Comment by ajarifi** [comment]
import Pkg; Pkg.add("Documenter")

this is also needed in the make.jl.

**Comment by ohno** [comment]
I updated the Developer's Guide (https://github.com/ohno/Antique.jl/commit/44c767f2169a586035d917401ad18ca3377a5a45) and developer tools (https://github.com/ohno/Antique.jl/commit/5ae74a26c93f17cee4eb5f43c51aab65ca66e040). Dependencies will be installed automatically.

By th way, Weave.jl has already been eliminated from this package.
