### ISSUE TITLE
Comment on Hydrogen atom

### ISSUE THREAD

**Issue by ajarifi** [ohno/Antique.jl#37]
For hydrogen atoms, I think it should be mentioned that only the coulomb potential is included in the model.
For realistic hydrogen atoms, more interactions should be included. 

Also, I think the muonic atom is also interesting.
The difference is that the electron mass is replaced by muon mass.
I do not know if a separate module should be made or included in the hydrogen atom.

In the definition of Hamiltonian, I think the kinetic energy includes the Laplacian operator.
Not only d^2/dr^2.

**Comment by lhapp27** [comment]
If I am not mistaken, the general coulomb problem is already included in the module HydrogenAtom, by using the reduced mass instead of the electron mass as input, right? Then it might be the best to rename the module and keep the special case of the (purely-coulomb) Hydrogen Atom within the documentation, what do you think? I think having the same module twice is confusing, also as Jafar mentioned the actual Hydrogen Atom has more features than the pure Coulomb potential.

**Comment by ohno** [comment]
Yes, we use reduced mass $\mu$ in the general Coulomb problem. It's not impossible to treat for the general Coulomb problem with the current code, but it's very complicated.

The current implementations of the energy $E_n$ and the radial function $R_{nl}(r)$ do not explicitly depend on the masses ($m_\mathrm{e}$, $m_\mathrm{p}$ or $\mu$).
```math
    E_n = -\frac{Z^2}{2n^2} E_\mathrm{h}
```
and
```math
R_{nl}(r) = -\sqrt{\frac{(n-l-1)!}{2n(n+l)!} \left(\frac{2Z}{n a_0}\right)^3} \left(\frac{2Zr}{n a_0}\right)^l \exp \left(-\frac{Zr}{n a_0}\right) L_{n+l}^{2l+1} \left(\frac{2Zr}{n a_0}\right)
```
must be changed to
```math
    E_n = -\frac{Z^2}{2n^2} \frac{\mu}{m_\mathrm{e}} E_\mathrm{h}
```
and
```math
	R_{nl}(r) = -\sqrt{\frac{(n-l-1)!}{2n(n+l)!} \left(\frac{2Z}{n a_\mu}\right)^3} \left(\frac{2Zr}{n a_\mu}\right)^l \exp \left(-\frac{Zr}{n a_\mu}\right) L_{n+l}^{2l+1} \left(\frac{2Zr}{n a_\mu}\right).
```

Here I used $\frac{1}{\mu}=\frac{1}{m_\mathrm{e}}+\frac{1}{m_\mathrm{p}}$ and $a_\mu = a_0 \frac{m_\mathrm{e}}{\mu}$. Therefore we must change the $a_0$ and $E_\mathrm{h}$, not the mass $m_\mathrm{e}$:

- $E_\mathrm{h} \rightarrow \frac{\mu}{m_\mathrm{e}} E_\mathrm{h}$,
- $a_0 \rightarrow a_0 \frac{m_\mathrm{e}}{\mu}$.

This is too difficult for users. I think new model is needed for the general Coulomb 2-body system. The model name will be `:TwoBodyCoulomb` or `:CoulombTwoBody`.

I updated the documentation for hydrogen atom.

**Comment by ohno** [comment]
@ajarifi I added "The potential includes only Coulomb interaction and it does not include fine or hyperfine interactions in this model." and modified kinetic term of Hamiltonian. Please check the documentation for hydrogen atom.
https://ohno.github.io/Antique.jl/stable/HydrogenAtom/

Please close this issue if it is enough. Or submit PR if it is not enough.

**Comment by ajarifi** [comment]
I think it is okay from my side. so, I will close #37
