### ISSUE TITLE
Improve test and docs generation

### ISSUE THREAD

**Issue by lhapp27** [ohno/Antique.jl#45]
During development of a new module, the steps:

6. Execute include("./developer/test.jl") to run tests. It will take few minutes to complete.
7. Execute include("./developer/docs.jl") to compile documents. HTML files (docs/build/*.html) will be generated. Please check them with Chrome or any other web browsers.

can be a bit time consuming while debugging, as the tests and documentation are always performed for **all** existing modules. In other words there is always a lot of repition of already tested and documented modules. It would be good to have either some automatic check or simple option to perform these steps only for the currently changed or selected module.

**Comment by ohno** [comment]
I agree completely. Testing of all models is not required for developments and patch version updates. I will change the testing method and the developer's guide.
