### ISSUE TITLE
Commonize special polynomials

### ISSUE THREAD

**Issue by ohno** [ohno/Antique.jl#51]
We currently prioritize each model being independent and self-contained. Some orthogonal polynomials can be made common. Reconsider whether the code should be common before updating to v1.0.0. This issue is related to https://github.com/ohno/Antique.jl/issues/49.

**Comment by lhapp27** [comment]
I think the same holds true also for the spherical harmonics. All (spherical symmetric) 3D problems they can use the same common function.

**Comment by ohno** [comment]
I gave priority to that all member functions are self-contained in each file.

Also, Commonization of spherical harmonic functions, etc. does not change　the Public API. Therefore, commonization can be done after the release of a major version 1.0.0 if we need.
