### ISSUE TITLE
English Proofreading

### ISSUE THREAD

**Issue by ohno** [ohno/Antique.jl#65]
Could you proofread the documentation? Please check [README.md](https://github.com/ohno/Antique.jl) in particular carefully. index.md is almost same as README.md.

**Comment by ajarifi** [comment]
The README.md looks fine to me. 

But, there is a small typo here:
`Write documnetation in this file. Include at least the definition of the Hamiltonian and the analytical solutions (eigenvalues and eigenfunctions). Calls a docstring in the source code (src/ModelName.jl) .`

I think it should be "documentation" and "Call".

**Comment by ohno** [comment]
@ajarifi Thank you! I updated README.md.

**Comment by ohno** [comment]
@lhapp27 Please close this issue after you check README.md.

**Comment by ajarifi** [comment]
Just another comment, but not very important. 
The Figure labels $r$ and $\psi$ look rather small. It may be better if they are bigger.

**Comment by ajarifi** [comment]
Anyway, it is good that you have added the demonstration. I think it is a good example of the application in research.

**Comment by ajarifi** [comment]
> Just another comment, but not very important. The Figure labels r and ψ look rather small. It may be better if they are bigger.

Anyway, do not worry about this at the moment. It is not crucial.

**Comment by lhapp27** [comment]
I checked the README.md file, see related pull request #67 . Proofreading the entire documentation is quite a lot and a rather tedious, since the text is located in two separate files (docstrings in source code and extra markdown file). Maybe we can automate that with some spellchecking software?
