### ISSUE TITLE
3D isotropic harmonic oscillator

### ISSUE THREAD

**Issue by ohno** [ohno/Antique.jl#7]
Implement the module of `:HarmonicOscillator3D`. The analytical solutions are written in [Wikipedia](https://en.wikipedia.org/wiki/Quantum_harmonic_oscillator#Example:_3D_isotropic_harmonic_oscillator) or Messiah's Quantum Mechanics. The code will be almost similar to the code of [hydrogen atom](https://github.com/ohno/Antique.jl/blob/main/src/HydrogenAtom.jl).

The spherical harmonics are used in the [hydrogen atom](https://ohno.github.io/Antique.jl/dev/HydrogenAtom/#Spherical-Harmonics).

https://github.com/ohno/Antique.jl/blob/2994e17ee8dd233a6d47c0cdeeefc1c8d4bfe413/src/HydrogenAtom.jl#L32-L39

The generalized Laguerre polynomials are used in [Morse potential](https://ohno.github.io/Antique.jl/dev/MorsePotential/#Generalized-Laguerre-Polynomials).

https://github.com/ohno/Antique.jl/blob/2994e17ee8dd233a6d47c0cdeeefc1c8d4bfe413/src/MorsePotential.jl#L41-L42

**Comment by ajarifi** [comment]
Hi

**Comment by ohno** [comment]
Thank you for your pull request. I marged it. You can see the hidden document page here:
https://ohno.github.io/Antique.jl/dev/HarmonicOscillator3D/

**Comment by ohno** [comment]
By the way, the minimum value of $n$ is 1 in hydrogen atom. Is not the minimum value in 3D harmonic oscillator 0? I'm not sure.

**Comment by ajarifi** [comment]
> By the way, the minimum value of n is 1 in hydrogen atom. Is not the minimum value in 3D harmonic oscillator 0? I'm not sure.

I think it is from n=0 for harmonic oscillator.

**Comment by ohno** [comment]
According to [S. Flügge, _Practical Quantum Mechanics_ (Springer Berlin Heidelberg, 1999)](https://archive.org/details/PracticalQuantumMechanicsS.Flgge/page/n183/mode/2up), this model seems to be called a Spherical oscilator. It seems better to use `:SphericalOscillator` for the isotropic three-dimensional harmonic oscillator and reserve `:HarmonicOscillator3D` for the anisotropic 3D harmonic oscillator.


By the way, the Kummer's (confluent hypergeometric) function $M(a, b, z) =_1 F_1(a ; b ; z)$ is used for the eigen functions.

```math
u(r, \vartheta, \varphi) = C r^{\prime} \mathrm{e}^{-\frac{\lambda}{2} r^2}{ }_1 F_1\left(-n_r, l+\frac{3}{2} ; \lambda r^2\right) Y_{l, m}(\vartheta, \varphi)
```

This is consistent to the solution using the generalized Laguerre polynomials:

```math
L_n^{(\alpha)}(x) = \left(\begin{array}{c}
n+\alpha \\
n
\end{array}\right) M(-n, \alpha+1, x)
```

Please see [Wikipedia](https://en.wikipedia.org/wiki/Laguerre_polynomials#Explicit_examples_and_properties_of_the_generalized_Laguerre_polynomials).
